### ISSUE TITLE
As a user, I want to have my learning progress tracked locally, so that I can continue from where I left.

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/saiba#161]
### Background

We need to implement the _User Progress_ functionality from Platypus in Saiba, which allows the user's learning progress to persist.

In this user story, we'll focus solely on making storing and retrieving the user progress locally and not yet on any interaction with the backend or the user's account.

### Goal

Have a working local _User Progress_ functionality.

### Acceptance criteria

- [x] The user's progress is tracked as they complete goals of the learning unit
- [x] The progress indicators in the sidebar update accordingly
- [x] The progress persists when they navigate to other routes
- [x] The progress persists across browser sessions (after closing the page)

### Out of scope

- Connecting the progress with an account in the backend
- User account "Learning" page

### Future of feature

After this is completed, we can start working on connecting the local progress with the user account's progress in the backend.

### Resources

- Example of functionality: https://learn.qiskit.org/course/introduction/why-quantum-computing (Complete widget interactions and continue doing so in the next pages to see the progress in the sidebar)

### Tasks

- [x] https://github.com/Qiskit/saiba/issues/35
- [x] https://github.com/Qiskit/saiba/issues/164

**Comment by Tansito** [comment]
All tasks are completed and the progress is being stored locally. We need to fix some bugs but we are taking them into account in #180 .
