### ISSUE TITLE
As a user, I want to have some simple widgets available, so that I can learn more dynamically.

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/saiba#167]
### Background

We need to continue with the migration of the widgets from Platypus to Saiba.

This user story focuses on some rather _simple_ widgets. Their migration will also serve as a blueprint for future widget migrations.

### Goal

Migrate some _simple_ widgets to Saiba.

### Acceptance criteria

- [x] The **Block** widget and all its variants (Exercise, Reminder & Tabs) are available in Saiba in some page
- [x] The **Carousel** widget is available in Saiba in some page
- [x] The **Binary** widget is available in Saiba in some page
- [x] All widgets implement the support for tracking events developed in [this user story](https://github.com/Qiskit/saiba/issues/162)

By "in some page" we mean that the widget should be accessible via a URL (only in a local development environment is fine). That could be an example page [like this](https://learn.qiskit.org/course/examples/widgets). The important part is that we're able to test the UI.

### Out of scope

- Migrating any other component

### Future of feature

After this, we can continue migrating more widgets.

### Resources

- Widgets examples: https://learn.qiskit.org/course/examples/widgets

### Tasks

- [x] https://github.com/Qiskit/saiba/issues/193
- [x] https://github.com/Qiskit/saiba/issues/156
- [x] https://github.com/Qiskit/saiba/issues/149
- [x] https://github.com/Qiskit/saiba/issues/155
- [x] https://github.com/Qiskit/saiba/issues/227
- [ ] https://github.com/Qiskit/saiba/issues/233

**Comment by vabarbosa** [comment]
can be closed. the test will be addressed as part a greater test revisit
