### ISSUE TITLE
As a user, I want to have my learning progress stored in the server, so that I can continue after I finish my browser session.

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/saiba#180]
### Background

We need to implement the _User Progress_ functionality from Platypus in Saiba, which allows the user's learning progress to persist.

In [a previous user story](https://github.com/Qiskit/saiba/issues/161), we focused on developing a way to store the progress client-side. In this user story, we'll focus on storing and retrieving the user progress in the server when the user is logged in to their account.

### Goal

Have a working _User Progress_ functionality that stores the progress in the server.

### Acceptance criteria

- [x] The user's progress is stored in the server as they complete goals of the learning unit
- [x] The progress indicators in the sidebar update accordingly
- [ ] The user can update their progress, login in a new browser, and have the same progress there
- [ ] After login out, the progress resets to the initial state (no progress)
- [x] ~When a guest makes some progress and then creates a new account, the progress is added to that user account~ (Won't do. See https://github.com/Qiskit/saiba/issues/191#issuecomment-1294730643)
- [x] ~When a guest makes some progress and then logs in, the new progress is added on top of the existing user account's progress~ (Won't do. See https://github.com/Qiskit/saiba/issues/191#issuecomment-1294730643)
- [ ] When a guest makes some progress and then creates a new account, the account starts with no progress
- [ ] When a guest makes some progress and then logs in, the account's progress overwrites the local progress

### Out of scope

- User account "Learning" page

### Resources

- Example of functionality: https://learn.qiskit.org/course/introduction/why-quantum-computing:
  - Complete widget interactions and continue doing so in the next pages to see the progress in the sidebar
  - Then create a user account
  - Login to that account from another browser and see how the progress is retrieved from the backend

### Tasks

- [x] https://github.com/Qiskit/saiba/issues/190
- [x] https://github.com/Qiskit/saiba/issues/189
- [x] ~https://github.com/Qiskit/saiba/issues/191~
- [x] https://github.com/Qiskit/saiba/issues/254
- [x] #65
