### ISSUE TITLE
Recreate the user learning page

### ISSUE THREAD

**Issue by vabarbosa** [Qiskit/saiba#263]
### Feature description

- [x] private & public & syllabi tabs #269 
- [ ] course cards in private tab #290 
- [x] course list in public tab #200 
- [x] ~~syllabi list in syllabi tab~~ descoped

### Additional information

[Figma private experience](https://www.figma.com/file/KCfjq5xQHg0C1JmcrE3CGx/1332-Private-Experience?node-id=1422%3A105754)

**Comment by yoshiemuranaka** [comment]
After our discussion, we decided to hide the `Private content` tab if the user is not enrolled in any cohort. The user should be emailed when they are added/removed from a cohort.

**Comment by yoshiemuranaka** [comment]
@JRussellHuffman @gracelindsell a quick follow-up from a meeting we just finished

We are still defining how we're going to group 'learning paths' (chapters, tutorials, etc)  together as shown on the learning page of the new design. Just so we aren't blocked, I'm going to move forward by displaying all courses (except private ones) on the Learning page which is the same implementation that we have currently in platypus

New design


![Image](https://user-images.githubusercontent.com/8097306/199801020-68c30f97-e61c-47dc-adae-9b1d3b491eb1.png)




Current platypus implementation 



![Image](https://user-images.githubusercontent.com/8097306/199801040-aea8a523-0a72-4046-bfd1-f2d9d8b8b29d.png)

**Comment by JRussellHuffman** [comment]
Makes sense to me. Thanks!

@gracelindsell, I see on the designs that the icon next to each item is square, while the implemented version is a circle. Seeing the two next to each other, I think the circle makes the most sense, because that is how we have it represented in other parts of the platform. But do you know if the designs are shown as square for a particular reason? I don't want to override that decision if we thought it through already.
