### ISSUE TITLE
As a developer, I want to manage the access to private courses, so that I can invite and control the access to my courses

### ISSUE THREAD

**Issue by Tansito** [Qiskit/saiba#300]
### Background

Now that we are going to provide support to upload your own content and generate **custom courses** we need to implement a way to manage the people that have access to those courses.

### Goal

Implement a set of steps to facilitate to the user invite and manage who has permissions to access to its courses.

### Acceptance criteria

- [x] A course administrator can create cohorts to manage the access to their courses.
- [x] A course administrator can update the information of their cohorts.
- [x] A course administrator can view a list of the cohorts that include a course owned by them (only the cohorts that they are an admin of).
- [x] A user can only see the courses that belong to a cohort they are a member of.

### Out of scope

- E-mail invitations to cohorts.

### Future of feature

- E-mail invitations.

### Resources

- Design: https://www.figma.com/file/KCfjq5xQHg0C1JmcrE3CGx/1332-Private-Experience

### Tasks

- #306 
- #88
- https://github.com/Qiskit/saiba/issues/376
- https://github.com/Qiskit/saiba/issues/388
- Feature branch **feat/cohort**:
  - https://github.com/Qiskit/saiba/issues/334
  - https://github.com/Qiskit/saiba/issues/333
  - https://github.com/Qiskit/saiba/issues/331
  - https://github.com/Qiskit/saiba/issues/332
  - #89

**Comment by lerongil** [comment]
Note from sprint review: We may use the generated invite link as an interim solution until email implementation is available.

**Comment by abdonrd** [comment]
Done!
