### ISSUE TITLE
As a learner, I want to be able to navigate and refresh the page without the need to sign-in one time and another, so that we will store the session in local storage.

### ISSUE THREAD

**Issue by Tansito** [Qiskit/saiba#307]
### Background

The user must be able to close the tab and return with a session every time it enters in the platform again.

### Goal

Implement local storage to doesn't loose the session once time the user close the tab without logs-out.

### Acceptance criteria

- [ ] The user is able to refresh the page and continue in its account.
- [ ] If user logs-out the data is cleared in local storage.
- [ ] Once time the user logs-out should be able to navigate without break anything.

### Tasks

- #280
- #297
