### ISSUE TITLE
[EPIC] Flow Control Checkbox

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/saiba#364]
### Background

In order to prevent users to proceed to certain pages before completing a page ([**Flow Control v1** milestone](https://github.com/Qiskit/saiba/milestone/27)), we need to create a way to mark pages as completed.

For some pages we have widgets (like quizzes). When successfully completed, we can asume that the page is completed and that the user can proceed.

For other pages, we don't have those widgets, so we need a way to know that the user has completed that page.

### Goal

Create a **Flow Control Checkbox** component that lets the user tell us when they have completed the page by checking the box.

### Acceptance criteria

- [ ] When a user checks the **Flow Control Checkbox**, the page is marked as completed and the user can proceed with the next piece of content (if any is available).
- [ ] When the **Flow Control Checkbox** is unchecked, the page is **not yet** marked as completed and the user **cannot** proceed.
- [ ] The **Flow Control Checkbox** is added to all pieces of content that don't include any other widget with goals.
- [ ] Race conditions (by clicking the checkbox multiple times very fast) are avoided with our implementation.

### Out of scope

- Further logic regarding the Flow Control feature.

### Resources

- Design: https://www.figma.com/file/KCfjq5xQHg0C1JmcrE3CGx/1332-Private-Experience?node-id=1881%3A160652&t=Xss25ok6FSmZW5JG-0

### Tasks

- [ ] https://github.com/Qiskit/saiba/issues/355
- [ ] https://github.com/Qiskit/saiba/issues/356
- [ ] https://github.com/Qiskit/saiba/issues/357

**Comment by abdonrd** [comment]
@Qiskit/qiskit-digital-devs Would it make sense to try to automate this?
For example, if there is no widget inside the content, automatically show the checkbox.

**Comment by techtolentino** [comment]
@abdonrd - that would be ideal, in my opinion... 

but also, this should only be available for units that "require flow control"

**Comment by Tansito** [comment]
I don't know if this can help, I assume that the logic should be just check if the unit has goals or not (apart of the control flow requirement).

**Comment by eddybrando** [comment]
From discussions led by @techtolentino and @JRussellHuffman, we've determined that the Flow Control will be set at the Course level.

If a Course requires Flow Control, the units will always show the checkbox widget and require it to be checked to proceed to the next unit.

If a Course does not require Flow Control, the user can navigate the units as they wish.

**Comment by yoshiemuranaka** [comment]
UI work is on hold until new branding designs are available
