### ISSUE TITLE
[EPIC] Mega Menu with grouped courses

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/saiba#365]
### Background

In [the current textbook](https://learn.qiskit.org/course/ch-prerequisites/environment-setup-guide-to-work-with-qiskit-textbook), our Mega Menu displays a list of the available courses, which are grouped:

![image](https://user-images.githubusercontent.com/22047320/205111843-90c8f15a-04da-4bbd-ad91-3bb9529caea2.png)

These groups are hardcoded and there is no representation of them in the database.

We need to have this data structure represented in our database so that we can reuse it in the Mega Menu, in the Learning page and maybe in other parts too.

### Goal

Adjust our courses data structure so that the grouping currently shown in Platypus is represented there as well.

### Acceptance criteria

- [ ] The groups structure is represented in the database and not hardcoded in the Mega Menu.
- [ ] The Mega Menu shows the grouped courses.

### Out of scope

- Reusing this grouping in any other part (like the Learning page)

### Future of feature

- Reuse this grouping in the Learning page
- Assess if we could use this grouping in other parts of the application

### Tasks

- [ ] https://github.com/Qiskit/saiba/issues/97

**Comment by yoshiemuranaka** [comment]
After examining the different course groupings on qiskit.org/learn mega menu, we determined that most of the groups were a type of course, except tutorial.

- We are proposing adding a **`Course`** `type` field that could be _default_, _chapter_, or _summer-school_.

- The tutorials in the mega menu are just external links. We think it may be ok to hard-code the tutorial section, but if we want it represented in the DB we could consider creating a **`Resource`** model that would have `title`, `url`, `description`, and `image` fields. 



Some outstanding questions that came from our discussions that we'd like to follow up on:

- Should we include the mega menu dropdown at all in the course progression section. The thinking was that it may add confusion to accelerator users. 
- Will course landing pages be migrated to saiba? 
- Could any of the course "types" be consolidated/removed? This is related to some of the inconsistent terminology used throughout the textbook. We will probably need a larger discussion around our terminology

**Comment by yoshiemuranaka** [comment]
@JRussellHuffman before we implement any backend changes needed for the mega menu, do you have any thoughts around:

> - Should we include the mega menu dropdown at all in the course progression section. The thinking was that it may add confusion to accelerator users.
> - Could any of the course "types" be consolidated/removed? This is related to some of the inconsistent terminology used throughout the textbook. We will probably need a larger discussion around our terminology

Should we hold off on these changes until we have the discussion around naming/terminology?

**Comment by JRussellHuffman** [comment]
1. Do you mean including the megamenu above the course progress section (the way it is currently implemented for free users)? Personally, I think it would be weird to remove access to free content for the premium users but maybe  it's more nuanced than that.
2. In this case, do you "courses", "chapters", "tutorials", and "summer schools"? I don't think that's confusing to our users, or at least, I haven't heard of any issues with it. We should definitely still discuss terminology, but I think our current terminology issues are our own, not necessarily user facing issues. But maybe I'm wrong.

**Comment by yoshiemuranaka** [comment]
1. Yes. While we were discussing the different course types, the question came up of whether or not the mega menu dropdown is useful (for public content users) and whether or not it would be confusing for private content users. Just wanted to surface to you since it came up and a few thought it should be removed.
2. Yes, as we were auditing the current textbook UI, the create/view community syllabi was confusing to a few of us. We couldn't immediately tell what was a course/chapter/unit. We're not the users, but it seems like our backend naming of units is different than how it is organized in the syllabi UI. I think someone also mentioned that `chapters` was an older term used and we may not want to use it going forward

@vabarbosa @techtolentino @abdonrd correct me if I'm wrong or missed anything.



<img width="1092" alt="Screenshot 2022-12-12 at 2 25 56 PM" src="https://user-images.githubusercontent.com/8097306/207168876-2dc36d43-7d34-42d7-9a1e-c5fd7d4f05e0.png">

<img width="1191" alt="Screenshot 2022-12-12 at 2 29 27 PM" src="https://user-images.githubusercontent.com/8097306/207169210-09fd44df-3aba-42a9-81ab-7abe584f99af.png">

**Comment by yoshiemuranaka** [comment]
We agreed to use the terms:
- Lesson
- Unit
- Resource
- Learning path

There should be changes made on the backend to support the new terminology. During sprint planning, we agreed to move the mega menu issue forward (before updating the backend) by adding all the courses to the dropdown which is done in #346 

<img width="1261" alt="Screenshot 2022-12-19 at 1 57 30 PM" src="https://user-images.githubusercontent.com/8097306/209366255-1a8f7ee9-415c-4886-8105-324918b96dad.png">
