### ISSUE TITLE
[EPIC] Vue.js Pinia Store syntax refactor

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/saiba#368]
### Background

We've been working with [Pinia Setup Stores](https://pinia.vuejs.org/core-concepts/#setup-stores) and have had some issues, like when clearing all of the stores states, which we currently need to do one store at a time for each store do to the limitations of the Setup Store.

For this and other reasons we were thinking about changing to the [Options Store](https://pinia.vuejs.org/core-concepts/#option-stores) syntax.

### Goal

Investigate if a changes from the Pinia Setup Store to the Options Store could benefit us and, if so, implement that refactor.

### Acceptance criteria

- [ ] We've discussed pros and cons of the syntax change.
- [ ] The results of the discussion are documented (like in GitHub Discussions).
- [ ] We've changed all stores to be Options Stores (if we decide that's the best syntax).

### Out of scope

- Anything related to changing our components or any other part of the codebase to Options syntax other than the Pinia Stores.

### Tasks

- [ ] https://github.com/Qiskit/saiba/issues/264
- [ ] Discuss pros and cons of Pinia Setup Stores vs Pinia Options Stores
- [ ] Refactor Pinia Stores to the Options Stores syntax (if necessary)
