### ISSUE TITLE
[EPIC] Available routes

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/saiba#374]
### Background

We need to define what routes we want to have available. This is a complex task since we need to cover multiple cases for both public and private pages, and also consider possible slugs conflicts due to similarly named lessons. 

### Goal

Define a logic for the available routes that cover our use cases and implement it.

### Acceptance criteria

- [x] We have discussed the strategies for defining the available routes.
- [x] We have documented the agreed upon logic for routes in Saiba.
- [x] The required changes to the routes are implemented:
  - [x] Account pages
  - [x] Authentication pages
  - [x] Public Textbook courses
  - [x] Private courses
  - [x] Syllabi

### Tasks

- [x] https://github.com/Qiskit/saiba/issues/316
- [x] https://github.com/Qiskit/saiba/issues/380
- [x] https://github.com/Qiskit/saiba/issues/375
- [x] ~Change routes of the Authentication pages~ (No changes required)
- [x] https://github.com/Qiskit/saiba/issues/377
- [x] https://github.com/Qiskit/saiba/issues/378
- [x] https://github.com/Qiskit/saiba/issues/379
- [x] https://github.com/Qiskit/saiba/issues/381

**Comment by vabarbosa** [comment]
thank you!
